(function(g){var window=this;var cqa=function(a,b){return g.Vb(a,b)},f5=function(a,b,c){a.l.set(b,c)},g5=function(a){f5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},h5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.Vm(a.l,b,c)},dqa=function(a,b){var c=[];
g.Yi(b,function(d){try{var e=g.Zn.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.Yn(e)&&c.push(d):c.push(d)},a);
return c},eqa=function(a,b){var c=dqa(a,b);
(0,g.z)(c,function(d){g.Zn.prototype.remove.call(this,d)},a)},i5=function(a){if(a.hd){if(a.hd.locationOverrideToken)return{locationOverrideToken:a.hd.locationOverrideToken};
if(null!=a.hd.latitudeE7&&null!=a.hd.longitudeE7)return{latitudeE7:a.hd.latitudeE7,longitudeE7:a.hd.longitudeE7}}return null},fqa=function(a,b){g.ab(a,b)||a.push(b)},j5=function(a){var b=0,c;
for(c in a)b++;return b},k5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},l5=function(){},gqa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},hqa=function(a){if(a.Fc&&"function"==typeof a.Fc)return a.Fc();
if(g.u(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},iqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.u(a))(0,g.z)(a,b,void 0);else{if(a.Qd&&"function"==typeof a.Qd)var c=a.Qd();else if(a.Fc&&"function"==typeof a.Fc)c=void 0;else if(g.La(a)||g.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=hqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},jqa=function(a,b,c,d){var e=new g.Jm(null,void 0);
a&&g.Km(e,a);b&&g.Lm(e,b);c&&g.Mm(e,c);d&&(e.i=d);return e},m5=function(a,b){g.bp[a]=!0;
var c=g.$o();c&&c.publish.apply(c,arguments);g.bp[a]=!1},n5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Gm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",kqa(this,a.capabilities||""),lqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},kqa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Qa(cqa,mqa)).forEach(function(c){a.capabilities.add(c)})},lqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},o5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},p5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},q5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nqa=function(a){return new o5(a)},r5=function(a){return g.Ka(a)?(0,g.B)(a,nqa):[]},s5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},t5=function(a){return g.Ka(a)?"["+(0,g.B)(a,s5).join(",")+"]":"null"},u5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},oqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},v5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},w5=function(a,b){return g.Ya(a,function(c){return p5(c,b)})},x5=function(a){try{var b=(0,g.As)(),c=(0,g.zs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},pqa=function(){var a=(0,g.zs)();
a&&eqa(a,a.g.nf(!0))},y5=function(){var a=g.Cs("yt-remote-connected-devices")||[];
g.qb(a);return a},qqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},z5=function(a){g.Bs("yt-remote-connected-devices",a,86400)},B5=function(){if(A5)return A5;
var a=g.Cs("yt-remote-device-id");a||(a=u5(),g.Bs("yt-remote-device-id",a,31536E3));for(var b=y5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return A5=d},C5=function(){var a=y5(),b=B5();
g.ab(a,b);g.Ds()&&g.sb(a,b);a=qqa(a);if(0==a.length)try{g.yr("remote_sid")}catch(c){}else try{g.xr("remote_sid",a.join(","),-1)}catch(c){}},D5=function(){return g.Cs("yt-remote-session-browser-channel")},E5=function(){return g.Cs("yt-remote-local-screens")||[]},F5=function(){g.Bs("yt-remote-lounge-token-expiration",!0,86400)},rqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(E5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.eh)(c,function(d){return!g.ab(b,d)})&&F5();
g.Bs("yt-remote-local-screens",a,31536E3)},sqa=function(a,b){g.Bs("yt-remote-session-browser-channel",a);
g.Bs("yt-remote-session-screen-id",b);var c=y5(),d=B5();g.ab(c,d)||c.push(d);z5(c);C5()},G5=function(a){a||(x5("yt-remote-session-screen-id"),x5("yt-remote-session-video-id"));
C5();a=y5();g.db(a,B5());z5(a)},I5=function(){if(!H5){var a=g.jo();
a&&(H5=new g.Tn(a))}return H5?!!H5.get("yt-remote-use-staging-server"):!1},J5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},K5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},M5=function(a){a.length?L5(a.shift(),function(){M5(a)}):N5()},tqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},L5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},N5=function(){var a=K5();
a&&a(!1,"No cast extension found")},O5=function(){if(uqa){var a=2,b=K5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;L5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",N5,c)}},vqa=function(){O5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);M5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},P5=function(a,b,c){g.H.call(this);
this.B=null!=c?(0,g.y)(a,c):a;this.Xc=b;this.A=(0,g.y)(this.pD,this);this.g=!1;this.i=0;this.l=this.Ca=null;this.o=[]},Q5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return gqa(a)},R5=function(){},S5=function(){},T5=function(){},V5=function(a){return(a=U5(a))?new ActiveXObject(a):new XMLHttpRequest},U5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},W5=function(a,b,c,d){this.g=a;
this.l=b;this.D=c;this.B=d||1;this.o=45E3;this.ca=new g.dY(this);this.i=new g.al;this.i.setInterval(250)},Y5=function(a,b,c){a.ai=1;
a.Yf=g5(b.clone());a.rh=c;a.A=!0;X5(a,null)},Z5=function(a,b,c,d,e){a.ai=1;
a.Yf=g5(b.clone());a.rh=null;a.A=c;e&&(a.jA=!1);X5(a,d)},X5=function(a,b){a.Fi=(0,g.D)();
$5(a);a.Dg=a.Yf.clone();h5(a.Dg,"t",a.B);a.al=0;a.tc=a.g.Hp(a.g.Nk()?b:null);0<a.nq&&(a.Un=new g.dl((0,g.y)(a.jB,a,a.tc),a.nq));a.ca.ea(a.tc,"readystatechange",a.gM);var c=a.Zg?g.cc(a.Zg):{};a.rh?(a.Fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Dg,a.Fo,a.rh,c)):(a.Fo="GET",a.jA&&!g.Ld&&(c.Connection="close"),a.tc.send(a.Dg,a.Fo,null,c));a.g.ze(1)},g6=function(a,b,c){for(var d=!0;!a.Og&&a.al<c.length;){var e=wqa(a,c);
if(e==a6){4==b&&(a.pg=4,b6(15),d=!1);break}else if(e==c6){a.pg=4;b6(16);d=!1;break}else d6(a,e)}4==b&&0==c.length&&(a.pg=1,b6(17),d=!1);a.Ae=a.Ae&&d;d||(e6(a),f6(a))},wqa=function(a,b){var c=a.al,d=b.indexOf("\n",c);
if(-1==d)return a6;c=Number(b.substring(c,d));if(isNaN(c))return c6;d+=1;if(d+c>b.length)return a6;var e=b.substr(d,c);a.al=d+c;return e},j6=function(a,b){a.Fi=(0,g.D)();
$5(a);var c=b?window.location.hostname:"";a.Dg=a.Yf.clone();f5(a.Dg,"DOMAIN",c);f5(a.Dg,"t",a.B);try{a.Ee=new ActiveXObject("htmlfile")}catch(n){e6(a);a.pg=7;b6(22);f6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in h6)k=h6[l];else if(l in i6)k=h6[l]=i6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
h6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.rc("b/12014412"),d+"</body></html>");a.Ee.open();a.Ee.write(g.Mc(c));a.Ee.close();a.Ee.parentWindow.m=(0,g.y)(a.wL,a);a.Ee.parentWindow.d=(0,g.y)(a.rz,a,!0);a.Ee.parentWindow.rpcClose=(0,g.y)(a.rz,a,!1);c=a.Ee.createElement("DIV");a.Ee.parentWindow.document.body.appendChild(c);d=g.Cc(a.Dg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.ze(1)},$5=function(a){a.mt=(0,g.D)()+a.o;
k6(a,a.o)},k6=function(a,b){if(null!=a.Vi)throw Error("WatchDog timer not null");
a.Vi=l6((0,g.y)(a.GL,a),b)},m6=function(a){a.Vi&&(g.w.clearTimeout(a.Vi),a.Vi=null)},f6=function(a){a.g.nw()||a.Og||a.g.In(a)},e6=function(a){m6(a);
g.Bi(a.Un);a.Un=null;a.i.stop();g.fY(a.ca);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Ee&&(a.Ee=null)},d6=function(a,b){try{a.g.lz(a,b),a.g.ze(4)}catch(c){}},o6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;n6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){o6(a,b,c,d,f)},f)})}},n6=function(a,b,c){var d=new Image;
d.onload=function(){try{p6(d),c(!0)}catch(e){}};
d.onerror=function(){try{p6(d),c(!1)}catch(e){}};
d.onabort=function(){try{p6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{p6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
k5(d,a)},p6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},q6=function(a){this.g=a;
this.i=new R5},s6=function(a){var b=r6(a.g,a.fj,"/mail/images/cleardot.gif");
g5(b);o6(b.toString(),5E3,(0,g.y)(a.xC,a),3,2E3);a.ze(1)},u6=function(a){var b=a.g.G;
if(null!=b)b6(5),b?(b6(11),t6(a.g,a,!1)):(b6(12),t6(a.g,a,!0));else if(a.Hd=new W5(a,void 0,void 0,void 0),a.Hd.Zg=a.lq,b=a.g,b=r6(b,b.Nk()?a.Jj:null,a.mq),b6(5),!g.Jd||g.md(10))h5(b,"TYPE","xmlhttp"),Z5(a.Hd,b,!1,a.Jj,!1);else{h5(b,"TYPE","html");var c=a.Hd;a=!!a.Jj;c.ai=3;c.Yf=g5(b.clone());j6(c,a)}},v6=function(a){g.qk.call(this);
this.headers=new g.Gm;this.N=a||null;this.i=!1;this.S=this.g=null;this.Z=this.F="";this.A=0;this.l="";this.o=this.aa=this.D=this.R=!1;this.B=0;this.G=null;this.X="";this.J=this.T=!1},xqa=function(a){return g.Jd&&g.kd(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},yqa=function(a){return"content-type"==a.toLowerCase()},y6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.A=5;w6(a);x6(a)},w6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},B6=function(a){if(a.i&&"undefined"!=typeof g.jY)if(a.S[1]&&4==z6(a)&&2==a.getStatus())A6(a,"Local request error detected and ignored");
else if(a.D&&4==z6(a))g.bl(a.pw,0,a);else if(a.dispatchEvent("readystatechange"),4==z6(a)){A6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.tf(1,String(a.F));if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!zqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<z6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";w6(a)}}finally{x6(a)}}},x6=function(a,b){if(a.g){C6(a);
var c=a.g,d=a.S[0]?g.Ha:null;a.g=null;a.S=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},C6=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.G&&(g.w.clearTimeout(a.G),a.G=null)},z6=function(a){return a.g?a.g.readyState:0},D6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},A6=function(a,b){return b+" ["+a.Z+" "+a.F+" "+a.getStatus()+"]"},E6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.A=new R5;this.F=a||null;this.G=null!=b?b:null;this.B=c||!1},Aqa=function(a,b){this.g=a;
this.map=b;this.context=null},F6=function(a){g.Sj.call(this,"statevent",a)},G6=function(a,b){g.Sj.call(this,"timingevent",a);
this.size=b},H6=function(a){g.Sj.call(this,"serverreachability",a)},L6=function(a){I6(a);
if(3==a.g){var b=a.rk++,c=a.gm.clone();f5(c,"SID",a.l);f5(c,"RID",b);f5(c,"TYPE","terminate");J6(a,c);b=new W5(a,a.l,b,void 0);b.ai=2;b.Yf=g5(c.clone());k5(new Image,b.Yf.toString());b.Fi=(0,g.D)();$5(b)}K6(a)},N6=function(a){a.PC(1,0);
a.gm=r6(a,null,a.kq);M6(a)},I6=function(a){a.fg&&(a.fg.abort(),a.fg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.qf&&(g.w.clearTimeout(a.qf),a.qf=null);O6(a);a.Dd&&(a.Dd.cancel(),a.Dd=null);a.ng&&(g.w.clearTimeout(a.ng),a.ng=null)},P6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Aqa(a.LH++,b));2!=a.g&&3!=a.g||M6(a)},M6=function(a){a.Dd||a.ng||(a.ng=l6((0,g.y)(a.qz,a),0),a.Th=0)},S6=function(a,b){if(1==a.g){if(!b){a.rk=Math.floor(1E5*Math.random());
var c=a.rk++,d=new W5(a,"",c,void 0);d.Zg=null;var e=Q6(a),f=a.gm.clone();f5(f,"RID",c);f5(f,"CVER","1");J6(a,f);Y5(d,f,e);a.Dd=d;a.g=2}}else 3==a.g&&(b?R6(a,b):0==a.i.length||a.Dd||R6(a))},R6=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.rk-1;var d=Q6(a)}else c=b.D,d=b.rh;else c=a.rk++,d=Q6(a);var e=a.gm.clone();f5(e,"SID",a.l);f5(e,"RID",c);f5(e,"AID",a.ni);J6(a,e);c=new W5(a,a.l,c,a.Th+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Dd=c;Y5(c,e,d)},J6=function(a,b){if(a.Uc){var c=a.Uc.Nv();
c&&g.Kb(c,function(d,e){f5(b,e,d)})}},Q6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},T6=function(a){a.Sb||a.qf||(a.D=1,a.qf=l6((0,g.y)(a.pz,a),0),a.Mh=0)},V6=function(a){if(a.Sb||a.qf||3<=a.Mh)return!1;
a.D++;a.qf=l6((0,g.y)(a.pz,a),U6(a,a.Mh));a.Mh++;return!0},t6=function(a,b,c){a.Do=c;
a.Je=b.Df;a.B||N6(a)},O6=function(a){null!=a.Tg&&(g.w.clearTimeout(a.Tg),a.Tg=null)},U6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},X6=function(a,b){if(2==b||9==b){var c=null;
a.Uc&&(c=null);var d=(0,g.y)(a.KM,a);c||(c=new g.Jm("//www.google.com/images/cleardot.gif"),g5(c));n6(c.toString(),1E4,d)}else b6(2);W6(a,b)},W6=function(a,b){a.g=0;
a.Uc&&a.Uc.Lu(b);K6(a);I6(a)},K6=function(a){a.g=0;
a.Je=-1;if(a.Uc)if(0==a.o.length&&0==a.i.length)a.Uc.tp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Uc.tp(b)}},r6=function(a,b,c){var d=g.Rm(c);
if(""!=d.g)b&&g.Lm(d,b+"."+d.g),g.Mm(d,d.A);else{var e=window.location;d=jqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.sj&&g.Kb(a.sj,function(f,k){f5(d,k,f)});
f5(d,"VER",a.Pg);J6(a,d);return d},l6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},b6=function(a){Y6.dispatchEvent(new F6(Y6,a))},Z6=function(){},$6=function(){this.g=[];
this.i=[]},Bqa=function(a,b){this.action=a;
this.params=b||{}},a7=function(a,b){g.H.call(this);
this.g=new g.K(this.oL,0,this);g.J(this,this.g);this.Xc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},b7=function(a,b,c){this.I=a;
this.B=b;this.l=new g.Sn;this.i=new a7(this.qM,this);this.g=null;this.gb=!1;this.A=null;this.G="";this.F=this.o=0;this.D=[];this.J=c||!1},Cqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Do,sessionId:a.g.l,arrayId:a.g.ni}},c7=function(a,b){a.F=b||0;
a.i.stop();a.g&&(3==a.g.g&&S6(a.g),L6(a.g));a.F=0},d7=function(a){return!!a.g&&3==a.g.g},Dqa=function(a,b){(a.B.loungeIdToken=b)||a.i.stop()},e7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.tf(4,a))||"";b&&(this.port=":"+b);this.domain=g.uf(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},f7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ef(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.A,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Up(b,a)},Eqa=function(){var a=h7;
i7();j7.push(a);k7(j7)},l7=function(a,b){i7();
var c=j7,d=Fqa(a,String(b));0==c.length?Gqa(d):(k7(c),(0,g.z)(c,function(e){e(d)}))},i7=function(){j7||(j7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",j7,void 0))},Gqa=function(a){var b=(m7+1)%50;
m7=b;n7[b]=a;o7||(o7=49==b)},k7=function(a){var b=n7;
if(b[0]){var c=m7,d=o7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
n7=Array(50);m7=-1;o7=!1}},Fqa=function(a,b){var c=((0,g.D)()-Hqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},p7=function(a){g.O.call(this);
this.D=a;this.g=[]},q7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Iqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(f){return!!v5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=q7(a,b[d])||c;return c},Jqa=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},r7=function(a,b,c,d){g.O.call(this);
this.B=a;this.A=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ca=NaN},t7=function(a){p7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;s7(this);this.info("Initializing with "+t5(this.g))},u7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=f7(a.l,"/pairing/get_lounge_token_batch");
g7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.zD,a),(0,g.y)(a.yD,a))}},s7=function(a){var b=r5(E5());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return Iqa(a,b)},v7=function(a,b){rqa((0,g.B)(a.g,q5));
b&&F5()},x7=function(a,b){g.O.call(this);
this.B=b;var c=g.Cs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.A=a;this.l=this.o=NaN;this.i=null;w7("Initialized with "+g.sm(this.g))},y7=function(a,b,c){var d=f7(a.A,"/pairing/get_screen_availability");
g7(a.A,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},z7=function(a,b){a:if(j5(b)!=j5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(w7("Updated online screens: "+g.sm(a.g)),a.g=b,a.O("screenChange"));Kqa(a)},A7=function(a){isNaN(a.l)||g.Zo(a.l);
a.l=g.Xo((0,g.y)(a.ws,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},w7=function(a){l7("OnlineScreenService",a)},B7=function(a){var b={};
(0,g.z)(a.B(),function(c){c.token?b[c.token]=c.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},Kqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Bs("yt-remote-online-screen-ids",a.join(","),60):x5("yt-remote-online-screen-ids")},C7=function(a){p7.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.o=[];this.A={};Lqa(this)},E7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.A[b]);var k=a.Rd();if(k=(c?w5(k,c):null)||w5(k,b)){k.uuid=b;var l=D7(a,k);y7(a.i,l,function(m){e(m?l:null)})}else c?Mqa(a,c,(0,g.y)(function(m){var n=D7(this,new o5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));y7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},F7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Mqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Up(f7(a.B,"/pairing/get_lounge_token_batch"),e)},G7=function(a){a.g=a.l.Rd();
var b=a.A,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+t5(a.g))},Lqa=function(a){H7(a);
a.l=new t7(a.B);a.l.subscribe("screenChange",(0,g.y)(a.HD,a));G7(a);a.o=r5(g.Cs("yt-remote-automatic-screen-cache")||[]);H7(a);a.info("Initializing automatic screens: "+t5(a.o));a.i=new x7(a.B,(0,g.y)(a.Rd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.O("onlineScreenChange")},a))},D7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=w5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Bs("yt-remote-automatic-screen-cache",(0,g.B)(a.o,q5)));H7(a);a.A[b.uuid]=b.id;g.Bs("yt-remote-device-id-map",a.A,31536E3);return b},H7=function(a){a.A=g.Cs("yt-remote-device-id-map")||{}},I7=function(a,b,c){g.O.call(this);
this.S=c;this.G=a;this.i=b;this.l=null},J7=function(a,b){l7(a.S,b)},L7=function(a,b){I7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.B=(0,g.y)(this.rN,this);this.A=(0,g.y)(this.RL,this);this.o=g.Xo((0,g.y)(function(){K7(this,null)},this),12E4)},Nqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.sm(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){J7(this,"Failed to send message: getMdxSessionStatus.")},a)):J7(a,"Sending yt message without session: "+g.sm(b))},K7=function(a,b){g.Zo(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Kn,a),d=(0,g.y)(a.Ud,a);a.ew(b,c,d,5)}}else a.Ud(Error("Waiting for session status timed out."))},M7=function(a,b,c){I7.call(this,a,b,"DialSession");
this.o=this.F=null;this.I="";this.N=c;this.A=null;this.D=g.Ha;this.B=NaN;this.J=(0,g.y)(this.uN,this);this.g=g.Ha},N7=function(a){a.g=a.G.oB(a.I,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Kn(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Ud(b)},a))},O7=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.A){var c=a.A.currentTime||0;b.v=a.A.videoId;b.t=c}I5()&&(b.env_useStageMdx=1);return g.Cf(b)},P7=function(a,b){I7.call(this,a,b,"ManualSession");
this.g=g.Xo((0,g.y)(this.oi,this,null),150)},Q7=function(a,b,c,d){g.O.call(this);
this.i=a;this.D=b||"233637DE";this.B=c||"cl";this.F=d||!1;this.g=null;this.A=!1;this.l=[];this.o=(0,g.y)(this.wK,this)},R7=function(a,b){return b?g.Ya(a.l,function(c){return p5(b,c.label)},a):null},S7=function(a){l7("Controller",a)},h7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},T7=function(a){return a.A||!!a.l.length||!!a.g},U7=function(a,b,c){b!=a.g&&(g.Bi(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.oz,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.oi(null)):a.O("yt-remote-cast2-session-change",null))},V7=function(a){var b=a.i.nB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&p5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=R7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Rqa=function(a,b,c,d,e,f,k){Oqa()?Pqa(b,e,f,k)&&(X7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Y7(a,c):(window.__onGCastApiAvailable=function(l,m){l?Y7(a,c):(Z7("Failed to load cast API: "+m),$7(!1),X7(!1),x5("yt-remote-cast-available"),x5("yt-remote-cast-receiver"),a8(),c(!1))},d?g.jp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?vqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?N5():(O5(),M5(Qqa.map(tqa))))):W7("Cannot initialize because not running Chrome")},a8=function(){W7("dispose");
var a=b8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);c8(!1);g.ep(d8);d8.length=0},e8=function(){return!!g.Cs("yt-remote-cast-installed")},f8=function(){var a=g.Cs("yt-remote-cast-receiver");
return a?a.friendlyName:null},g8=function(){W7("clearCurrentReceiver");
x5("yt-remote-cast-receiver")},h8=function(){return e8()?b8()?b8().getCastSession():(Z7("getCastSelector: Cast is not initialized."),null):(Z7("getCastSelector: Cast API is not installed!"),null)},j8=function(){e8()?b8()?i8()?(W7("Requesting cast selector."),b8().requestSession()):(W7("Wait for cast API to be ready to request the session."),d8.push(g.dp("yt-remote-cast2-api-ready",j8))):Z7("requestCastSelector: Cast is not initialized."):Z7("requestCastSelector: Cast API is not installed!")},k8=function(a,
b){i8()?b8().setConnectedScreenStatus(a,b):Z7("setConnectedScreenStatus called before ready.")},Oqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.qw||a},Sqa=function(a,b){b8().init(a,b)},Pqa=function(a,b,c,d){var e=!1;
b8()||(a=new Q7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Bs("yt-remote-cast-available",f);m5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){W7("onReceiverSelected: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f);m5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){W7("onReceiverResumed: "+f.friendlyName);
g.Bs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){W7("onSessionChange: "+s5(f));
f||x5("yt-remote-cast-receiver");m5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
W7("cloudview.createSingleton_: "+e);return e},b8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Y7=function(a,b){$7(!0);
X7(!1);Sqa(a,function(c){c?(c8(!0),g.gp("yt-remote-cast2-api-ready")):(Z7("Failed to initialize cast API."),$7(!1),x5("yt-remote-cast-available"),x5("yt-remote-cast-receiver"),a8());b(c)})},W7=function(a){l7("cloudview",a)},Z7=function(a){l7("cloudview",a)},$7=function(a){W7("setCastInstalled_ "+a);
g.Bs("yt-remote-cast-installed",a)},i8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},c8=function(a){W7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},X7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},l8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.B=this.D=0;this.g=null;this.hasNext=this.Ke=!1;this.G=this.F=this.i=this.o=0;this.l=NaN;this.A=!1;this.reset(a)},m8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ke=!1;a.hasNext=!1;a.D=0;a.B=(0,g.D)();a.o=0;a.i=0;a.F=0;a.G=0;a.l=NaN;a.A=!1},n8=function(a){return 1==a.playerState?((0,g.D)()-a.B)/1E3:0},o8=function(a,b){a.D=b;
a.B=(0,g.D)()},p8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.B)/1E3+a.D;
case -1E3:return 0}return a.D},q8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&m8(a)},r8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Ke;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.B;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.F;b.loadedTime=a.G;b.liveIngestionTime=a.l;return b},u8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.B=[];this.A=new $6;this.l=this.i=null;this.G=(0,g.y)(this.tI,this);this.D=(0,g.y)(this.vk,this);this.F=(0,g.y)(this.sI,this);this.I=(0,g.y)(this.HI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qt,this),s8(this))):c=3;0!=c&&(b?this.qt(c):g.Xo((0,g.y)(function(){this.qt(c)},this),0));
var d=h8();d&&t8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},v8=function(a){return new l8(a.o.getPlayerContextData())},s8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.B.push(this.o.subscribe(b,g.Qa(this.tK,b),this))},a)},w8=function(a){(0,g.z)(a.B,function(b){this.o.unsubscribeByKey(b)},a);
a.B.length=0},x8=function(a,b){var c=a.A;
50>c.g.length+c.i.length&&a.A.i.push(b)},z8=function(a,b,c){var d=v8(a);
o8(d,c);-1E3!=d.playerState&&(d.playerState=b);y8(a,d)},A8=function(a,b,c){a.o.sendMessage(b,c)},y8=function(a,b){w8(a);
a.o.setPlayerContextData(r8(b));s8(a)},t8=function(a,b){a.l&&(a.l.removeUpdateListener(a.G),a.l.removeMediaListener(a.D),a.vk(null));
a.l=b;a.l&&(l7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.G),a.l.addMediaListener(a.D),a.l.media.length&&a.vk(a.l.media[0]))},B8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=v8(a);b.contentId!=d.videoId&&l7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;o8(d,a.i.getEstimatedTime());y8(a,d)}else l7("CP","No cast media video. Ignoring state update.")},C8=function(a,b,c){return(0,g.y)(function(d){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),A8(this,b,c))},a)},D8=function(a,b,c){g.O.call(this);
this.A=NaN;this.J=!1;this.F=this.D=this.G=this.I=NaN;this.S=[];this.o=this.B=this.l=this.Oa=this.g=null;this.R=a;this.S.push(g.cr(window,"beforeunload",(0,g.y)(this.sD,this)));this.i=[];this.Oa=new l8;this.N=b.id;this.g=Tqa(this,c);this.g.subscribe("handlerOpened",this.xI,this);this.g.subscribe("handlerClosed",this.uI,this);this.g.subscribe("handlerError",this.vI,this);this.g.subscribe("handlerMessage",this.wI,this);Dqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Ds()&&g.Bs("yt-remote-session-video-id",d)},this)},E8=function(a){l7("conn",a)},Tqa=function(a,b){return new b7(f7(a.R,"/bc"),b)},F8=function(a,b){a.O("proxyStateChange",b)},Uqa=function(a){a.A=g.Xo((0,g.y)(function(){E8("Connecting timeout");
this.Qh(1)},a),2E4)},G8=function(a){g.Zo(a.A);
a.A=NaN},H8=function(a){g.Zo(a.I);
a.I=NaN},Vqa=function(a){I8(a);
a.G=g.Xo((0,g.y)(function(){J8(this,"getNowPlaying")},a),2E4)},I8=function(a){g.Zo(a.G);
a.G=NaN},L8=function(a,b){b&&(G8(a),H8(a));
b==(d7(a.g)&&isNaN(a.A))?b&&(F8(a,1),J8(a,"getSubtitlesTrack")):b?(a.cw()&&a.Oa.reset(),F8(a,1),J8(a,"getNowPlaying"),K8(a)):a.Qh(1)},Wqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.O("remotePlayerChange"))},M8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;q8(a.Oa,c,d);a.O("remoteQueueChange")},Xqa=function(a,b){b.params=b.params||{};
M8(a,b);N8(a,b);a.O("autoplayDismissed")},N8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
o8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.G=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.F=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.A=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Vqa(a):I8(a);a.O("remotePlayerChange")},Yqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);o8(a.Oa,isNaN(c)?0:c);a.O("remotePlayerChange")}},Zqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.O("remotePlayerChange")},$qa=function(a,b){a.B=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},ara=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Ke="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.O("previousNextChange")},K8=function(a){g.Zo(a.F);
a.F=g.Xo((0,g.y)(a.Qh,a,1),864E5)},J8=function(a,b,c){c?E8("Sending: action="+b+", params="+g.sm(c)):E8("Sending: action="+b);
a.g.sendMessage(b,c)},O8=function(a){p7.call(this,"ScreenServiceProxy");
this.Wc=a;this.i=[];this.i.push(this.Wc.$_s("screenChange",(0,g.y)(this.pN,this)));this.i.push(this.Wc.$_s("onlineScreenChange",(0,g.y)(this.YJ,this)))},fra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Po("MDX_CONFIG")||b;pqa();C5();P8||(P8=new e7(b?b.loungeApiHost:void 0),I5()&&(P8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",Q8,void 0));bra();var c=R8();if(!c){var d=new C7(P8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=R8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Rqa(a,d,function(m){m?S8()&&k8(S8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){m5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),T8("Initializing: "+g.sm(b)),U8.push(g.dp("yt-remote-cast2-availability-change",function(){m5("yt-remote-receiver-availability-change")})),U8.push(g.dp("yt-remote-cast2-receiver-selected",function(){V8(null);
m5("yt-remote-auto-connect","cast-selector-receiver")})),U8.push(g.dp("yt-remote-cast2-receiver-resumed",function(){m5("yt-remote-receiver-resumed","cast-selector-receiver")})),U8.push(g.dp("yt-remote-cast2-session-change",cra)),U8.push(g.dp("yt-remote-connection-change",function(m){m?k8(S8(),"YouTube TV"):W8()||(k8(null,null),g8())})),a=X8(),b.isAuto&&(a.id+="#dial"),g.Lp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T8(" -- with channel params: "+
g.sm(a)),dra(a),c.start(),S8()||era())},gra=function(){var a=Y8();
e8()&&g.Cs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Y8=function(){var a=R8().Wc.$_gos();
var b=Z8();b&&$8()&&(v5(a,b)||a.push(b));return oqa(a)},a9=function(){var a=hra();
!a&&e8()&&f8()&&(a={key:"cast-selector-receiver",name:f8()});return a},hra=function(){var a=Y8(),b=Z8();
b||(b=W8());return g.Ya(a,function(c){return b&&p5(b,c.key)?!0:!1})},Z8=function(){var a=S8();
if(!a)return null;var b=R8().Rd();return w5(b,a)},cra=function(a){T8("remote.onCastSessionChange_: "+s5(a));
if(a){var b=Z8();b&&b.id==a.id?k8(b.id,"YouTube TV"):(b&&b9(),c9(a,1))}else $8()&&b9()},b9=function(){i8()?b8().stopSession():Z7("stopSession called before API ready.");
var a=$8();a&&(a.disconnect(1),d9(null))},e9=function(){var a=$8();
return!!a&&3!=a.getProxyState()},T8=function(a){l7("remote",a)},R8=function(){if(!f9){var a=g.x("yt.mdx.remote.screenService_");
f9=a?new O8(a):null}return f9},S8=function(){return g.x("yt.mdx.remote.currentScreenId_")},ira=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},jra=function(){return g.x("yt.mdx.remote.connectData_")},V8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},$8=function(){return g.x("yt.mdx.remote.connection_")},d9=function(a){var b=$8();
V8(null);a||ira("");g.Ga("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.z)(Q8,function(c){c(a)}),Q8.length=0);
b&&!a?m5("yt-remote-connection-change",!1):!b&&a&&m5("yt-remote-connection-change",!0)},W8=function(){var a=g.Ds();
if(!a)return null;var b=R8().Rd();return w5(b,a)},c9=function(a,b){Z8()&&Z8();
if(g9)h9=a;else{ira(a.id);var c=new D8(P8,a,X8());c.connect(b,jra());c.subscribe("beforeDisconnect",function(d){m5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){$8()&&d9(null)});
d9(c)}},era=function(){var a=W8();
a?(T8("Resume connection to: "+s5(a)),c9(a,0)):(G5(),g8(),T8("Skipping connecting because no session screen found."))},bra=function(){var a=X8();
if(g.Yb(a)){a=B5();var b=g.Cs("yt-remote-session-name")||"",c=g.Cs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},X8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},dra=function(a){a?(g.Bs("yt-remote-session-app",a.app),g.Bs("yt-remote-session-name",a.name)):(x5("yt-remote-session-app"),x5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.H.call(this);
this.A=a;this.i=b;this.l=new g.Or(this);g.J(this,this.l);this.l.L(b,"onCaptionsTrackListChanged",this.tJ);this.l.L(b,"captionschanged",this.rI);this.l.L(b,"captionssettingschanged",this.BA);this.l.L(b,"videoplayerreset",this.Ln);this.l.L(b,"mdxautoplaycancel",this.wC);this.R=this.l.L(b,"onVolumeChange",this.Yy);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.kz,this);c.subscribe("remotePlayerChange",this.xk,this);c.subscribe("remoteQueueChange",this.Ln,this);c.subscribe("autoplayUpNext",this.Ny,
this);c.subscribe("previousNextChange",this.hz,this);c.subscribe("nowAutoplaying",this.dz,this);c.subscribe("autoplayDismissed",this.My,this);this.suggestion=null;this.G=new g.PB(64);this.o=new g.K(this.zA,500,this);g.J(this,this.o);this.B=new g.K(this.AA,1E3,this);g.J(this,this.B);this.J=new P5(this.UM,0,this);g.J(this,this.J);this.D={};this.S=new g.K(this.bB,1E3,this);g.J(this,this.S);this.I=new g.dl(this.PF,1E3,this);g.J(this,this.I);this.N=g.Ha;this.BA();this.Ln();this.xk()},j9=function(a,b){a.A.Mc(b,
a.i.getVideoData().lengthSeconds)},kra=function(a){j9(a,0);
a.o.stop();k9(a,new g.PB(64))},m9=function(a,b){if(l9(a)&&!a.F){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.qA(a.i.getVideoData(1).videoId,c);a.D=v8(a.g).g}},n9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Me,i5(c));k9(a,new g.PB(1))},lra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{SQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.F=!1):(a.i.loadModule("captions"),a.F=!0)}else a.i.setOption("captions","track",{})},l9=function(a){return v8(a.g).videoId==a.i.getVideoData(1).videoId},k9=function(a,b){a.B.stop();
var c=a.G;if(!g.VB(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.TJ(a.i,d);a.G=b;mra(a.A,c,b)}},o9=function(){g.W.call(this,{C:"div",
H:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{C:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{C:"div",H:"ytp-mdx-popup-title",U:"You're signed out"},{C:"div",H:"ytp-mdx-popup-description",U:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{C:"div",H:"ytp-mdx-privacy-popup-buttons",K:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"Cancel"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
U:"Confirm"}]}]}]});this.l=new g.OP(this,250);g.J(this,this.l);this.D=this.i["ytp-mdx-privacy-popup-cancel"];this.L(this.D,"click",this.o);this.A=this.i["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},p9=function(a){g.W.call(this,{C:"div",
H:"ytp-remote",K:[{C:"div",H:"ytp-remote-display-status",K:[{C:"div",H:"ytp-remote-display-status-icon",K:[g.cP()]},{C:"div",H:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.OP(this,250);g.J(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);nra(this,g.PJ(a))},nra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.bN("Error on $RECEIVER_NAME",c):g.WB(b)||g.U(b,4)?g.bN("Playing on $RECEIVER_NAME",c):g.bN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},q9=function(a,b){g.xT.call(this,"Play on",0,a,b);
this.l=a;this.D={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},r9=function(a){g.tK.call(this,a);
this.i={key:u5(),name:"This computer"};this.A=null;this.o=[];this.I=this.g=null;this.F=[this.i];this.l=this.i;this.fk=new g.PB(64);this.J=0;this.Om=-1;this.B=null;if(!g.ny(g.X(this.player))){a=this.player;var b=g.IC(a);b&&(b=b.sn())&&(b=new q9(a,b),g.J(this,b));b=new p9(a);g.J(this,b);g.dK(a,b.element,4);this.B=new o9;g.J(this,this.B);g.dK(a,this.B.element,4);this.G=!!W8()}this.D=null},s9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},mra=function(a,b,
c){a.fk=c;
a.player.O("presentingplayerstatechange",new g.ZC(c,b))},t9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)b9();
else{var c;(c=!g.P(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.Po("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.Po("SESSION_INDEX")&&!g.Po("LOGGED_IN")))||a.G||!a.B);c||g.ny(g.X(a.player))||(g.WB(g.PJ(a.player))?a.player.pauseVideo():(a.D=(0,g.y)(a.XL,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.B&&a.B.l.show(),$8()||(g9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Me,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=i5(c))&&(d.locationInfo=c);c=d}else c=null;T8("Connecting to: "+g.sm(b));"cast-selector-receiver"==b.key?(V8(c||null),i8()?b8().setLaunchParams(c||null):Z7("setLaunchParams called before ready.")):!c&&e9()&&S8()==b.key?m5("yt-remote-connection-change",
!0):(b9(),V8(c||null),c=R8().Rd(),(c=w5(c,b.key))&&c9(c,1))}},i6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},h6={"'":"\\'"},ora={},mqa={ON:"atp",eQ:"ska",TP:"que",tP:"mus",dQ:"sus",LO:"dsp",aQ:"seq"};
n5.prototype.gg=function(){var a=new n5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var H5,A5="",uqa=J5("loadCastFramework")||J5("loadCastApplicationFramework"),Qqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(P5,g.H);g.h=P5.prototype;g.h.oD=function(a){this.o=arguments;this.g=!1;this.Ca?this.l=(0,g.D)()+this.Xc:this.Ca=g.bl(this.A,this.Xc)};
g.h.stop=function(){this.Ca&&(g.w.clearTimeout(this.Ca),this.Ca=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.B.apply(null,this.o)))};
g.h.V=function(){this.stop();P5.bb.V.call(this)};
g.h.pD=function(){this.l?(this.Ca=g.bl(this.A,this.l-(0,g.D)()),this.l=null):(this.Ca=null,this.i?this.g=!0:(this.g=!1,this.B.apply(null,this.o)))};R5.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
R5.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};S5.prototype.g=null;S5.prototype.getOptions=function(){var a;(a=this.g)||(a={},U5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var u9;g.Sa(T5,S5);u9=new T5;g.h=W5.prototype;g.h.Zg=null;g.h.Ae=!1;g.h.Vi=null;g.h.mt=null;g.h.Fi=null;g.h.ai=null;g.h.Yf=null;g.h.Dg=null;g.h.rh=null;g.h.tc=null;g.h.al=0;g.h.Ee=null;g.h.Fo=null;g.h.pg=null;g.h.Kj=-1;g.h.jA=!0;g.h.Og=!1;g.h.nq=0;g.h.Un=null;var c6={},a6={};g.h=W5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.gM=function(a){a=a.target;var b=this.Un;b&&3==z6(a)?b.Gj():this.jB(a)};
g.h.jB=function(a){try{if(a==this.tc)a:{var b=z6(this.tc),c=this.tc.A,d=this.tc.getStatus();if(g.Jd&&!g.md(10)||g.Ld&&!g.kd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bg&&!D6(this.tc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.ze(3):this.g.ze(2));m6(this);var e=this.tc.getStatus();this.Kj=e;var f=D6(this.tc);(this.Ae=200==e)?(4==b&&e6(this),this.A?(g6(this,b,f),g.bg&&this.Ae&&3==b&&(this.ca.ea(this.i,"tick",this.aM),this.i.start())):d6(this,f),this.Ae&&!this.Og&&(4==b?this.g.In(this):(this.Ae=
!1,$5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pg=3,b6(13)):(this.pg=0,b6(14)),e6(this),f6(this))}}catch(k){this.tc&&D6(this.tc)}finally{}};
g.h.aM=function(){var a=z6(this.tc),b=D6(this.tc);this.al<b.length&&(m6(this),g6(this,a,b),this.Ae&&4!=a&&$5(this))};
g.h.wL=function(a){l6((0,g.y)(this.vL,this,a),0)};
g.h.vL=function(a){this.Og||(m6(this),d6(this,a),$5(this))};
g.h.rz=function(a){l6((0,g.y)(this.uL,this,a),0)};
g.h.uL=function(a){this.Og||(e6(this),this.Ae=a,this.g.In(this),this.g.ze(4))};
g.h.cancel=function(){this.Og=!0;e6(this)};
g.h.GL=function(){this.Vi=null;var a=(0,g.D)();0<=a-this.mt?(2!=this.ai&&this.g.ze(3),e6(this),this.pg=2,b6(18),f6(this)):k6(this,this.mt-a)};
g.h.getLastError=function(){return this.pg};g.h=q6.prototype;g.h.lq=null;g.h.Hd=null;g.h.Vn=!1;g.h.ow=null;g.h.dm=null;g.h.Tq=null;g.h.mq=null;g.h.he=null;g.h.Df=-1;g.h.Jj=null;g.h.fj=null;g.h.connect=function(a){this.mq=a;a=r6(this.g,null,this.mq);b6(3);this.ow=(0,g.D)();var b=this.g.F;null!=b?(this.Jj=b[0],(this.fj=b[1])?(this.he=1,s6(this)):(this.he=2,u6(this))):(h5(a,"MODE","init"),this.Hd=new W5(this,void 0,void 0,void 0),this.Hd.Zg=this.lq,Z5(this.Hd,a,!1,null,!0),this.he=0)};
g.h.xC=function(a){if(a)this.he=2,u6(this);else{b6(4);var b=this.g;b.Je=b.fg.Df;X6(b,9)}a&&this.ze(2)};
g.h.Hp=function(a){return this.g.Hp(a)};
g.h.abort=function(){this.Hd&&(this.Hd.cancel(),this.Hd=null);this.Df=-1};
g.h.nw=function(){return!1};
g.h.lz=function(a,b){this.Df=a.Kj;if(0==this.he)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Je=this.Df;X6(c,2);return}this.Jj=c[0];this.fj=c[1]}else c=this.g,c.Je=this.Df,X6(c,2);else if(2==this.he)if(this.Vn)b6(7),this.Tq=(0,g.D)();else if("11111"==b){if(b6(6),this.Vn=!0,this.dm=(0,g.D)(),c=this.dm-this.ow,!g.Jd||g.md(10)||500>c)this.Df=200,this.Hd.cancel(),b6(12),t6(this.g,this,!0)}else b6(8),this.dm=this.Tq=(0,g.D)(),this.Vn=!1};
g.h.In=function(){this.Df=this.Hd.Kj;if(this.Hd.Ae)0==this.he?this.fj?(this.he=1,s6(this)):(this.he=2,u6(this)):2==this.he&&((!g.Jd||g.md(10)?!this.Vn:200>this.Tq-this.dm)?(b6(11),t6(this.g,this,!1)):(b6(12),t6(this.g,this,!0)));else{0==this.he?b6(9):2==this.he&&b6(10);var a=this.g;this.Hd.getLastError();a.Je=this.Df;X6(a,2)}};
g.h.Nk=function(){return this.g.Nk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ze=function(a){this.g.ze(a)};g.Sa(v6,g.qk);var zqa=/^https?$/i,pra=["POST","PUT"];g.h=v6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.A=0;this.Z=b;this.R=!1;this.i=!0;this.g=this.N?V5(this.N):V5(u9);this.S=this.N?this.N.getOptions():u9.getOptions();this.g.onreadystatechange=(0,g.y)(this.pw,this);try{l5(A6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){l5(A6(this,"Error opening Xhr: "+f.message));y6(this,f);return}a=c||"";
var e=this.headers.clone();d&&iqa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Qd(),yqa);c=g.w.FormData&&a instanceof g.w.FormData;!g.ab(pra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{C6(this),0<this.B&&(this.J=xqa(this.g),l5(A6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.B,this.g.ontimeout=(0,g.y)(this.qw,this)):this.G=g.bl(this.qw,this.B,this)),l5(A6(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){l5(A6(this,"Send error: "+f.message)),y6(this,f)}};
g.h.qw=function(){"undefined"!=typeof g.jY&&this.g&&(this.l="Timed out after "+this.B+"ms, aborting",this.A=8,A6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(A6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),x6(this))};
g.h.V=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),x6(this,!0));v6.bb.V.call(this)};
g.h.pw=function(){this.ga()||(this.aa||this.D||this.o?B6(this):this.vK())};
g.h.vK=function(){B6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<z6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.u(this.l)?this.l:String(this.l)};g.h=E6.prototype;g.h.sj=null;g.h.Dd=null;g.h.Sb=null;g.h.kq=null;g.h.gm=null;g.h.zu=null;g.h.xm=null;g.h.rk=0;g.h.LH=0;g.h.Uc=null;g.h.ng=null;g.h.qf=null;g.h.Tg=null;g.h.fg=null;g.h.Do=null;g.h.ni=-1;g.h.Yw=-1;g.h.Je=-1;g.h.Th=0;g.h.Mh=0;g.h.Pg=8;var Y6=new g.qk;g.Sa(F6,g.Sj);g.Sa(G6,g.Sj);g.Sa(H6,g.Sj);g.h=E6.prototype;g.h.connect=function(a,b,c,d,e){b6(0);this.kq=b;this.sj=c||{};d&&g.Da(e)&&(this.sj.OSID=d,this.sj.OAID=e);this.B?(l6((0,g.y)(this.Tu,this,a),100),N6(this)):this.Tu(a)};
g.h.Tu=function(a){this.fg=new q6(this);this.fg.lq=null;this.fg.i=this.A;this.fg.connect(a)};
g.h.nw=function(){return 0==this.g};
g.h.qz=function(a){this.ng=null;S6(this,a)};
g.h.pz=function(){this.qf=null;this.Sb=new W5(this,this.l,"rpc",this.D);this.Sb.Zg=null;this.Sb.nq=0;var a=this.zu.clone();f5(a,"RID","rpc");f5(a,"SID",this.l);f5(a,"CI",this.Do?"0":"1");f5(a,"AID",this.ni);J6(this,a);if(!g.Jd||g.md(10))f5(a,"TYPE","xmlhttp"),Z5(this.Sb,a,!0,this.xm,!1);else{f5(a,"TYPE","html");var b=this.Sb,c=!!this.xm;b.ai=3;b.Yf=g5(a.clone());j6(b,c)}};
g.h.lz=function(a,b){if(0!=this.g&&(this.Sb==a||this.Dd==a))if(this.Je=a.Kj,this.Dd==a&&3==this.g)if(7<this.Pg){try{var c=this.A.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Sb)if(this.Sb.Fi+3E3<this.Dd.Fi)O6(this),this.Sb.cancel(),this.Sb=null;else break a;V6(this);b6(19)}}else this.Yw=c[1],0<this.Yw-this.ni&&37500>c[2]&&this.Do&&0==this.Mh&&!this.Tg&&(this.Tg=l6((0,g.y)(this.nI,this),6E3));else X6(this,11)}else b!=ora.mO.g&&X6(this,11);else if(this.Sb==a&&
O6(this),!g.wb(b)){c=this.A.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ni=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.xm=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Uc&&this.Uc.Nu(),this.zu=r6(this,this.Nk()?this.xm:null,this.kq),T6(this)):"stop"==e[0]&&X6(this,7):3==this.g&&("stop"==e[0]?X6(this,7):"noop"!=e[0]&&this.Uc&&this.Uc.Mu(e),this.Mh=0)}}};
g.h.nI=function(){null!=this.Tg&&(this.Tg=null,this.Sb.cancel(),this.Sb=null,V6(this),b6(20))};
g.h.In=function(a){if(this.Sb==a){O6(this);this.Sb=null;var b=2}else if(this.Dd==a)this.Dd=null,b=1;else return;this.Je=a.Kj;if(0!=this.g)if(a.Ae)1==b?(b=(0,g.D)()-a.Fi,Y6.dispatchEvent(new G6(Y6,a.rh?a.rh.length:0,b,this.Th)),M6(this),this.o.length=0):T6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Je)){if(d=1==b)this.Dd||this.ng||1==this.g||2<=this.Th?d=!1:(this.ng=l6((0,g.y)(this.qz,this,a),U6(this,this.Th)),this.Th++,d=!0);d=!(d||2==b&&V6(this))}if(d)switch(c){case 1:X6(this,
5);break;case 4:X6(this,10);break;case 3:X6(this,6);break;case 7:X6(this,12);break;default:X6(this,2)}}};
g.h.PC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.KM=function(a){a?b6(2):(b6(1),W6(this,8))};
g.h.Hp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new v6;a.T=!1;return a};
g.h.isActive=function(){return!!this.Uc&&this.Uc.isActive(this)};
g.h.ze=function(a){Y6.dispatchEvent(new H6(Y6,a))};
g.h.Nk=function(){return!(!g.Jd||g.md(10))};
g.h=Z6.prototype;g.h.Nu=function(){};
g.h.Mu=function(){};
g.h.Lu=function(){};
g.h.tp=function(){};
g.h.Nv=function(){return{}};
g.h.isActive=function(){return!0};g.h=$6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Wma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Fc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Sa(a7,g.H);g.h=a7.prototype;g.h.oL=function(){this.Xc=Math.min(3E5,2*this.Xc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Xc+15E3*Math.random();g.un(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Xc=5E3};g.Sa(b7,Z6);g.h=b7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Lf=function(a){return this.l.ah(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.gb||(this.gb=!0,g.Bi(this.l),c7(this),g.Bi(this.i),this.i=null)};
g.h.ga=function(){return this.gb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.i.stop();this.A=a||null;this.o=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new E6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Uc=null);d.Uc=this;this.g=d;e?this.g.connect(a,b,this.B,e.l,e.ni):c?this.g.connect(a,b,this.B,c.sessionId,c.arrayId):this.g.connect(a,b,this.B)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):d7(this)&&P6(this.g,c)};
g.h.Nu=function(){this.i.reset();this.A=null;this.o=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)P6(this.g,a[b])}this.O("handlerOpened")};
g.h.Lu=function(a){var b=2==a&&401==this.g.Je;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.tp=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Nv=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.o&&(a.ui=""+this.o);0!=this.F&&(a.ui=""+this.F);this.A&&g.fc(a,this.A);return a};
g.h.Mu=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),L6(this.g)):this.O("handlerMessage",new Bqa(a[0],a[1]))};
g.h.qM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.Dd&&b++;0==b&&this.connect(this.A,this.o)};e7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.A=function(a){a(Error("request timed out"))};var Hqa=(0,g.D)(),j7=null,n7=Array(50),m7=-1,o7=!1;g.Sa(p7,g.O);p7.prototype.Rd=function(){return this.g};
p7.prototype.contains=function(a){return!!v5(this.g,a)};
p7.prototype.get=function(a){return a?w5(this.g,a):null};
p7.prototype.info=function(a){l7(this.D,a)};g.t(r7,g.O);g.h=r7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ca)&&this.mB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ca)||(g.Zo(this.Ca),this.Ca=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.mB=function(){this.Ca=NaN;this.g=g.Up(f7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.y)(this.nN,this),onError:(0,g.y)(this.mN,this),oe:(0,g.y)(this.oN,this)})};
g.h.nN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new o5(c))};
g.h.mN=function(a){this.g=null;a.status&&404==a.status?this.i>=qra.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=qra[this.i],this.Ca=g.Xo((0,g.y)(this.mB,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.oN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var qra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(t7,p7);g.h=t7.prototype;g.h.start=function(){s7(this)&&this.O("screenChange");!g.Cs("yt-remote-lounge-token-expiration")&&u7(this);g.Zo(this.i);this.i=g.Xo((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){s7(this);q7(this,a);v7(this,!1);this.O("screenChange");b(a);a.token||u7(this)};
g.h.remove=function(a,b){var c=s7(this);Jqa(this,a)&&(v7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.zo=function(a,b,c,d){var e=s7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,v7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.V=function(){g.Zo(this.i);t7.bb.V.call(this)};
g.h.zD=function(a){s7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}v7(this,!b);b&&l7(this.D,"Missed "+b+" lounge tokens.")};
g.h.yD=function(a){l7(this.D,"Requesting lounge tokens failed: "+a)};g.t(x7,g.O);g.h=x7.prototype;g.h.start=function(){var a=parseInt(g.Cs("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?A7(this):(this.o=(0,g.D)()+3E5,g.Bs("yt-remote-fast-check-period",this.o),this.ws())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){w7("Updating availability on schedule.");var a=this.B(),b=g.Lb(this.g,function(c,d){return c&&!!w5(a,d)},this);
z7(this,b)};
g.h.V=function(){g.Zo(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.ws=function(){g.Zo(this.l);this.l=NaN;this.i&&this.i.abort();var a=B7(this);if(j5(a)){var b=f7(this.A,"/pairing/get_screen_availability");this.i=g7(this.A,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.RK,this,a),(0,g.y)(this.QK,this))}else z7(this,{}),A7(this)};
g.h.RK=function(a,b){this.i=null;var c=g.Rb(B7(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;z7(this,d);A7(this)}else this.Ib("Changing Screen set during request."),this.ws()};
g.h.QK=function(a){this.Ib("Screen availability failed: "+a);this.i=null;A7(this)};
g.h.Ib=function(a){l7("OnlineScreenService",a)};g.Sa(C7,p7);g.h=C7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.zo=function(a,b,c,d){this.l.contains(a)?this.l.zo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,l7(this.D,a),d(Error(a)))};
g.h.Rd=function(a){return a?this.g:g.fb(this.g,(0,g.Vd)(this.o,function(b){return!this.contains(b)},this))};
g.h.nB=function(){return(0,g.Vd)(this.Rd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.oB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new r7(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.Bi(f);d(D7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Bi(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.qN=function(a,b,c,d){g.Up(f7(this.B,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new o5(f.screen||{});if(!k.name||F7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);F7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(D7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Bi(this.l);g.Bi(this.i);C7.bb.V.call(this)};
g.h.HD=function(){G7(this);this.O("screenChange");this.i.update()};
C7.prototype.dispose=C7.prototype.dispose;g.Sa(I7,g.O);g.h=I7.prototype;g.h.Kn=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Ud=function(a){this.ga()||(a&&J7(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){l7(this.S,a)};
g.h.qB=function(){return null};
g.h.Fs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){J7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Fs("");I7.bb.V.call(this)};g.Sa(L7,I7);g.h=L7.prototype;g.h.Es=function(a){if(this.g){if(this.g==a)return;J7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.B);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A)}this.g=a;this.g.addUpdateListener(this.B);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.A);Nqa(this)};
g.h.oi=function(a){this.info("launchWithParams no-op for Cast: "+g.sm(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Ud()},this),(0,g.y)(function(){this.Ud(Error("Failed to stop receiver app."))},this)):this.Ud(Error("Stopping cast device witout session."))};
g.h.Fs=g.Ha;g.h.V=function(){this.info("disposeInternal");g.Zo(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.B),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A));this.g=null;L7.bb.V.call(this)};
g.h.RL=function(a,b){if(!this.ga())if(b){var c=Q5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.sm(c));switch(d){case "mdxSessionStatus":K7(this,c.screenId);break;default:J7(this,"Unknown youtube message: "+d)}}else J7(this,"Unable to parse message.")}else J7(this,"No data in message.")};
g.h.ew=function(a,b,c,d){E7(this.G,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(J7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Xo((0,g.y)(this.ew,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.qB=function(){return this.g};
g.h.rN=function(a){this.ga()||a||(J7(this,"Cast session died."),this.Ud())};g.Sa(M7,I7);g.h=M7.prototype;g.h.Es=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.oi=function(a){this.A=a;this.D()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o?this.o.stop((0,g.y)(this.Ud,this,null),(0,g.y)(this.Ud,this,"Failed to stop DIAL device.")):this.Ud()};
g.h.V=function(){this.g();this.g=g.Ha;g.Zo(this.B);this.o&&this.o.removeUpdateListener(this.J);this.o=null;M7.bb.V.call(this)};
g.h.uN=function(a){this.ga()||a||(J7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Ud())};
g.h.Cq=function(a){this.I=u5();if(this.A){var b=new chrome.cast.DialLaunchResponse(!0,O7(this));a(b);N7(this)}else this.D=(0,g.y)(function(){g.Zo(this.B);this.D=g.Ha;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,O7(this));a(c);N7(this)},this),this.B=g.Xo((0,g.y)(function(){this.D()},this),100)};
g.h.dE=function(a,b,c){E7(this.G,this.F.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Kn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Cq(b,c)},this),(0,g.y)(function(d){J7(this,"Failed to get DIAL screen: "+d);
this.Cq(b,c)},this))};g.Sa(P7,I7);P7.prototype.stop=function(){this.Ud()};
P7.prototype.Es=g.Ha;P7.prototype.oi=function(){g.Zo(this.g);this.g=NaN;var a=w5(this.G.Rd(),this.i.label);a?this.Kn(a):this.Ud(Error("No such screen"))};
P7.prototype.V=function(){g.Zo(this.g);this.g=NaN;P7.bb.V.call(this)};g.Sa(Q7,g.O);g.h=Q7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.AK,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.nz,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.OI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.o),Eqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.pB,this)),this.l=V7(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(k){this.Ib("Failed to set initial custom receivers: "+g.sm(k))},this)),this.O("yt-remote-cast2-availability-change",T7(this)),b(!0))},this),(0,g.y)(function(k){this.Ib("Failed to initialize API: "+g.sm(k));
b(!1)},this))};
g.h.yM=function(a,b){S7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)S7("Unsetting old screen status: "+this.g.i.friendlyName),U7(this,null)}if(a&&b){if(!this.g){c=w5(this.i.Rd(),a);if(!c){S7("setConnectedScreenStatus: Unknown screen.");return}var d=R7(this,c);d||(S7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Ib("Failed to set initial custom receivers: "+g.sm(e))},this)));
S7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);U7(this,new P7(this.i,d),!0)}this.g.Fs(b)}else S7("setConnectedScreenStatus: no screen.")};
g.h.zM=function(a){this.ga()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.oi(a):this.Ib("Setting connection data without a session")};
g.h.tN=function(){this.ga()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),U7(this,null)):S7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.nz,this),(0,g.y)(this.XK,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.pB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.x("yt.mdx.remote.debug.handlers_")||[],h7);g.Bi(this.g);Q7.bb.V.call(this)};
g.h.Ib=function(a){l7("Controller",a)};
g.h.oz=function(a,b){this.g==a&&(b||U7(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.wK=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),S7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)S7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{S7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:U7(this,
new P7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:U7(this,new M7(this.i,a,this.B));break;case chrome.cast.ReceiverType.CAST:U7(this,new L7(this.i,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.OI=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return S7("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);U7(this,new M7(this.i,b,this.B))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.dE,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Cq,b))};
g.h.nz=function(a){if(!this.ga()){S7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)S7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),U7(this,new L7(this.i,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=w5(this.i.Rd(),c.label);d&&p5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(S7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Bi(this.g),this.g=new L7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.oz,this,this.g)),this.g.oi(null));this.g.Es(a)}}};
g.h.sN=function(){return this.g?this.g.qB():null};
g.h.XK=function(a){this.ga()||(this.Ib("Failed to estabilish a session: "+g.sm(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&U7(this,null))};
g.h.AK=function(a){S7("Receiver availability updated: "+a);if(!this.ga()){var b=T7(this);this.A=a==chrome.cast.ReceiverAvailability.AVAILABLE;T7(this)!=b&&this.O("yt-remote-cast2-availability-change",T7(this))}};
g.h.pB=function(){this.ga()||(this.l=V7(this),S7("Updating custom receivers: "+g.sm(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Ib("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",T7(this)))};
Q7.prototype.setLaunchParams=Q7.prototype.zM;Q7.prototype.setConnectedScreenStatus=Q7.prototype.yM;Q7.prototype.stopSession=Q7.prototype.tN;Q7.prototype.getCastSession=Q7.prototype.sN;Q7.prototype.requestSession=Q7.prototype.requestSession;Q7.prototype.init=Q7.prototype.init;Q7.prototype.dispose=Q7.prototype.dispose;var d8=[];l8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";m8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ke=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.B=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.F=a.duration,this.G=a.loadedTime,this.l=a.liveIngestionTime,this.A=
!isNaN(this.l))};
l8.prototype.isAdPlaying=function(){return 1081==this.playerState};
l8.prototype.getDuration=function(){return this.A?this.F+n8(this):this.F};
l8.prototype.clone=function(){return new l8(r8(this))};g.t(u8,g.O);g.h=u8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,C8(this,"play")):A8(this,"play"),z8(this,1,p8(v8(this))),this.O("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,C8(this,"pause")):A8(this,"pause"),z8(this,2,p8(v8(this))),this.O("remotePlayerChange")):x8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=v8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,C8(this,"seekTo",{newTime:a}))}else A8(this,"seekTo",{newTime:a});z8(this,3,a);this.O("remotePlayerChange")}else x8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,C8(this,"stopVideo")):A8(this,"stopVideo");var a=v8(this);a.index=-1;a.videoId="";m8(a);y8(this,a);this.O("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=v8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){l7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){l7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A8(this,"setVolume",e)}c.muted=b;c.volume=a;y8(this,c)}else x8(this,g.Qa(this.setVolume,a,b))};
g.h.qA=function(a,b){if(1==this.g){var c=v8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.sm(b.style),g.fc(d,c.g));A8(this,"setSubtitlesTrack",d);y8(this,c)}else x8(this,g.Qa(this.qA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();A8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=v8(this);d.audioTrackId=c;y8(this,d)}else x8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=v8(this);c=c||0;var m={videoId:a,currentIndex:c};q8(l,a,c);g.Da(b)&&(o8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.sm(k));A8(this,"setPlaylist",m);d||y8(this,l)};
g.h.Pn=function(a,b){if(1==this.g){if(a&&b){var c=v8(this);q8(c,a,b);y8(this,c)}A8(this,"previous")}else x8(this,g.Qa(this.Pn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=v8(this);q8(c,a,b);y8(this,c)}A8(this,"next")}else x8(this,g.Qa(this.nextVideo,a,b))};
g.h.ov=function(){1==this.g?A8(this,"dismissAutoplay"):x8(this,this.ov)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){w8(this);this.o=null;this.A.clear();t8(this,null);g.O.prototype.V.call(this)};
g.h.qt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.A.isEmpty();)b=a=this.A,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.tK=function(a,b){this.O(a,b)};
g.h.tI=function(a){if(!a)this.vk(null),t8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=v8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)l7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y8(this,b)}};
g.h.vk=function(a){l7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.F);if(this.i=a)this.i.addUpdateListener(this.F),B8(this),this.O("remotePlayerChange")};
g.h.sI=function(a){a?(B8(this),this.O("remotePlayerChange")):this.vk(null)};
g.h.Vs=function(){A8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.HI=function(){var a=h8();a&&t8(this,a)};
g.h.Ib=function(a){l7("CP",a)};g.t(D8,g.O);g.h=D8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;o8(this.Oa,m);this.o="UNSUPPORTED";E8("Connecting with setPlaylist and params: "+g.sm(l));this.g.connect({method:"setPlaylist",
params:g.sm(l)},a,D5())}else E8("Connecting without params"),this.g.connect({},a,D5());Uqa(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),F8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){G8(this);I8(this);H8(this);g.Zo(this.D);this.D=NaN;g.Zo(this.F);this.F=NaN;this.l=null;g.dr(this.S);this.S.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.B=this.i=this.Oa=this.g=null};
g.h.sD=function(){this.Qh(2)};
g.h.xI=function(){E8("Channel opened");this.J&&(this.J=!1,H8(this),this.I=g.Xo((0,g.y)(function(){E8("Timing out waiting for a screen.");this.Qh(1)},this),15E3));
sqa(Cqa(this.g),this.N)};
g.h.uI=function(){E8("Channel closed");isNaN(this.A)?G5(!0):G5();this.dispose()};
g.h.vI=function(a){G5();isNaN(this.Aj())?(E8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,E8("Channel error: "+a+" with reconnection in "+this.Aj()+" ms"),F8(this,2))};
g.h.wI=function(a){a.params?E8("Received: action="+a.action+", params="+g.sm(a.params)):E8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=Q5(a.params.devices);this.i=(0,g.B)(a,function(c){return new n5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
L8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
L8(this,!1);break;case "remoteConnected":var b=new n5(Q5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||fqa(this.i,b);
break;case "remoteDisconnected":b=new n5(Q5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":M8(this,a);break;case "nowPlaying":Xqa(this,a);break;case "onStateChange":N8(this,a);break;case "onAdStateChange":Yqa(this,a);break;case "onVolumeChanged":Zqa(this,a);break;case "onSubtitlesTrackChanged":Wqa(this,a);break;case "nowAutoplaying":$qa(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.O("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":ara(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:E8("Unrecognized action: "+a.action)}};
g.h.nM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&J8(this,"getNowPlaying")}};
g.h.iD=function(){var a=3;this.ga()||(a=0,isNaN(this.Aj())?d7(this.g)&&isNaN(this.A)&&(a=1):a=2);return a};
g.h.Qh=function(a){E8("Disconnecting with "+a);G8(this);this.O("beforeDisconnect",a);1==a&&G5();c7(this.g,a);this.dispose()};
g.h.hD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),q8(a,this.l,a.index));return r8(a)};
g.h.AM=function(a){var b=new l8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Zo(this.D),this.D=g.Xo((0,g.y)(this.nM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&p8(this.Oa)==p8(b)&&g.sm(this.Oa.g)==g.sm(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.O(d)},this)};
g.h.cw=function(){var a=this.g.B.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Aj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.bD=function(){return this.o||"UNSUPPORTED"};
g.h.cD=function(){return this.B||""};
g.h.lN=function(){if(!isNaN(this.Aj())){var a=this.g.i;g.vn(a.g);a.start()}};
g.h.vM=function(a,b){J8(this,a,b);K8(this)};
D8.prototype.subscribe=D8.prototype.subscribe;D8.prototype.unsubscribeByKey=D8.prototype.Lf;D8.prototype.getProxyState=D8.prototype.iD;D8.prototype.disconnect=D8.prototype.Qh;D8.prototype.getPlayerContextData=D8.prototype.hD;D8.prototype.setPlayerContextData=D8.prototype.AM;D8.prototype.getOtherConnectedRemoteId=D8.prototype.cw;D8.prototype.getReconnectTimeout=D8.prototype.Aj;D8.prototype.getAutoplayMode=D8.prototype.bD;D8.prototype.getAutoplayVideoId=D8.prototype.cD;D8.prototype.reconnect=D8.prototype.lN;
D8.prototype.sendMessage=D8.prototype.vM;g.t(O8,p7);g.h=O8.prototype;g.h.Rd=function(a){return this.Wc.$_gs(a)};
g.h.contains=function(a){return!!this.Wc.$_c(a)};
g.h.get=function(a){return this.Wc.$_g(a)};
g.h.start=function(){this.Wc.$_st()};
g.h.add=function(a,b,c){this.Wc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Wc.$_r(a,b,c)};
g.h.zo=function(a,b,c,d){this.Wc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Wc.$_ubk(this.i[a]);this.i.length=0;this.Wc=null;p7.prototype.V.call(this)};
g.h.pN=function(){this.O("screenChange")};
g.h.YJ=function(){this.O("onlineScreenChange")};
C7.prototype.$_st=C7.prototype.start;C7.prototype.$_gspc=C7.prototype.qN;C7.prototype.$_gsppc=C7.prototype.oB;C7.prototype.$_c=C7.prototype.contains;C7.prototype.$_g=C7.prototype.get;C7.prototype.$_a=C7.prototype.add;C7.prototype.$_un=C7.prototype.zo;C7.prototype.$_r=C7.prototype.remove;C7.prototype.$_gs=C7.prototype.Rd;C7.prototype.$_gos=C7.prototype.nB;C7.prototype.$_s=C7.prototype.subscribe;C7.prototype.$_ubk=C7.prototype.Lf;var h9=null,g9=!1,P8=null,Q8=null,f9=null,U8=[];g.t(i9,g.H);g.h=i9.prototype;
g.h.V=function(){g.H.prototype.V.call(this);this.o.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.kz,this);this.g.unsubscribe("remotePlayerChange",this.xk,this);this.g.unsubscribe("remoteQueueChange",this.Ln,this);this.g.unsubscribe("autoplayUpNext",this.Ny,this);this.g.unsubscribe("previousNextChange",this.hz,this);this.g.unsubscribe("nowAutoplaying",this.dz,this);this.g.unsubscribe("autoplayDismissed",this.My,this);this.g=this.A=null};
g.h.Ix=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!v8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==v8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Gj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.rI=function(a){this.J.oD(a)};
g.h.UM=function(a){this.Ix("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.BA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||m9(this,a)};
g.h.Yy=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.xk,this);var b=Math.round(a.volume);a=!!a.muted;var c=v8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.S.start();this.g.subscribe("remotePlayerChange",this.xk,this)}};
g.h.tJ=function(){g.Yb(this.D)||lra(this,this.D);this.F=!1};
g.h.kz=function(a,b){this.B.stop();2==b&&this.AA()};
g.h.xk=function(){if(l9(this)){this.o.stop();var a=v8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.A.Om=1;break;case 1082:case 1083:this.A.Om=0;break;default:this.A.Om=-1}switch(a.playerState){case 1081:case 1:k9(this,new g.PB(8));this.zA();break;case 1085:case 3:k9(this,new g.PB(9));break;case 1083:case 0:k9(this,new g.PB(2));this.I.stop();j9(this,this.i.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.PB(4));break;case 2:k9(this,new g.PB(4));j9(this,p8(a));
break;case -1:k9(this,new g.PB(64));break;case -1E3:k9(this,new g.PB(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=v8(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,lra(this,a));a=v8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.S.isActive()||this.bB()}else kra(this)};
g.h.hz=function(){this.i.O("mdxpreviousnextchange")};
g.h.Ln=function(){l9(this)||kra(this)};
g.h.wC=function(){this.g.ov()};
g.h.Ny=function(a){a&&!g.P(g.X(this.i).experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Up("/watch_queue_ajax",{method:"GET",ud:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.zL,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.zL=function(a,b){var c=new g.yA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.dz=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.My=function(){this.i.O("mdxautoplaycanceled")};
g.h.PF=function(a,b){-1==v8(this.g).playerState?n9(this,a):b&&this.g.seekTo(a)};
g.h.bB=function(){if(l9(this)){var a=v8(this.g);this.l.Qa(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.L(this.i,"onVolumeChange",this.Yy)}};
g.h.zA=function(){this.o.stop();if(!this.g.ga()){var a=v8(this.g);1==a.playerState&&k9(this,new g.PB(8));j9(this,p8(a));this.o.start()}};
g.h.AA=function(){this.B.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.B.start()};g.t(o9,g.W);o9.prototype.o=function(){m5("mdx-privacy-popup-cancel");this.l.hide()};
o9.prototype.B=function(){m5("mdx-privacy-popup-confirm");this.l.hide()};g.t(p9,g.W);p9.prototype.A=function(a){nra(this,a.state)};g.t(q9,g.xT);q9.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.tb(a,this.B,this),g.zT(this,(0,g.B)(a,this.B)),a=this.l.getOption("remote","currentReceiver"),this.me(this.B(a)),this.enable(!0)):this.enable(!1)};
q9.prototype.B=function(a){return a.key};
q9.prototype.ye=function(a){return"cast-selector-receiver"==a?"Cast...":this.D[a].name};
q9.prototype.Kc=function(a){g.xT.prototype.Kc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.kb()};g.t(r9,g.tK);g.h=r9.prototype;
g.h.create=function(){fra(g.ey(g.X(this.player)));this.o.push(g.dp("yt-remote-before-disconnect",this.oI,this));this.o.push(g.dp("yt-remote-connection-change",this.BK,this));this.o.push(g.dp("yt-remote-receiver-availability-change",this.iz,this));this.o.push(g.dp("yt-remote-auto-connect",this.zK,this));this.o.push(g.dp("yt-remote-receiver-resumed",this.yK,this));this.o.push(g.dp("mdx-privacy-popup-confirm",this.dM,this));this.o.push(g.dp("mdx-privacy-popup-cancel",this.cM,this));this.iz()};
g.h.load=function(){this.player.cancelPlayback();g.tK.prototype.load.call(this);this.A=new i9(this,this.player,this.g);var a=(a=jra())?a.currentTime:0;var b=e9()?new u8($8(),void 0):null;0==a&&b&&(a=p8(v8(b)));0!=a&&this.Mc(a);mra(this,this.fk,this.fk);g.BX(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.Ci(this.A,this.g);this.g=this.A=null;g.tK.prototype.unload.call(this);g.BX(this.player.app,5);s9(this)};
g.h.V=function(){g.ep(this.o);g.tK.prototype.V.call(this)};
g.h.Ye=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.Ix.apply(this.A,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Om};
g.h.kD=function(){return this.loaded?this.A.suggestion:null};
g.h.Ke=function(){return this.g?v8(this.g).Ke:!1};
g.h.hasNext=function(){return this.g?v8(this.g).hasNext:!1};
g.h.Mc=function(a,b){this.J=a||0;this.player.O("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=v8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.l+n8(a):a.l,isAtLiveHead:1>=(a.A?a.i+n8(a):a.i)-this.getCurrentTime(),loaded:a.G,seekableEnd:a.A?a.i+n8(a):a.i,seekableStart:0<a.o?a.o+
n8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Pn=function(){this.g&&this.g.Pn()};
g.h.oI=function(a){1==a&&(this.I=this.g?v8(this.g):null)};
g.h.BK=function(){var a=e9()?new u8($8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.I=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Bi(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,p8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.iz=function(){this.F=[this.i].concat(gra());var a=a9()||this.i;t9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.XL=function(a){!this.G&&g.aD(a,8)&&(this.player.pauseVideo(),s9(this))};
g.h.zK=function(){var a=a9();t9(this,a)};
g.h.yK=function(){this.l=a9()};
g.h.dM=function(){this.G=!0;s9(this);g9=!1;h9&&c9(h9,1);h9=null};
g.h.cM=function(){this.G=!1;s9(this);t9(this,this.i);this.l=this.i;g9=!1;h9=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?j8():t9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&j8(),!0):!1}};
g.h.Vs=function(){this.g.Vs()};
g.h.Db=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.QU.remote=r9;})(_yt_player);
